name: 'Create a GHAS trial survey link'
description: 'After a GHAS trial you can share a link to a trial survey with customers'
inputs:
  survey_id:
    description: 'ID of the survey for which to create a weblink.'
    required: true
  surveymonkey_token:
    description: 'Valid access token for Surveymonkey.'
    required: true
  name:
    description: 'Name of the weblink. This should be the name of a customer.'
    required: true
  days_open:
    description: 'How many days this weblink should be accessible. Default: 14 days.'
    default: 14
    required: false
outputs:
  link:
    description: 'The weblink URL to the survey.'
    value: ${{ steps.createlink.outputs.link }}
runs:
  using: composite
  steps:
  - name: Create survey link
    id: createlink
    working-directory: ${{ github.action_path }}
    shell: bash
    env:
      INPUTS_SURVEY_ID: ${{ inputs.survey_id }}
      INPUTS_SURVEYMONKEY_TOKEN: ${{ inputs.surveymonkey_token }}
      INPUTS_NAME: ${{ inputs.name }}
      INPUTS_DAYS_OPEN: ${{ inputs.days_open }}
    run: |
      echo "::set-output name=link::$(./create-survey-link "$INPUTS_SURVEY_ID" "$INPUTS_NAME" "$INPUTS_DAYS_OPEN")"
